categories: "Categories"
search: "Search in posts"
tags: "Tags"
tagcloud: "Tag Cloud"
tweets: "Tweets"
prev: "Prev"
next: "Next"
comment: "Comments"
archive_a: "Archives"
archive_b: "Archives: %s"
page: "Page %d"
recent_posts: "Recent Posts"
read_more: "Read more"
